FROM node:12.18-alpine3.12

WORKDIR /usr/src/app

ENV PORT=3000
ARG NODE_ENV=development

COPY package.json package-lock.json ./
RUN npm install
COPY . .

EXPOSE $PORT

ENTRYPOINT [ "npm", "run", "watch" ]