FROM node:12.18-alpine3.12

WORKDIR /usr/src/app

ENV PORT=3000
ENV NODE_ENV=development
ENV MOUNT_PATH=/phpmyadmin/

COPY package.json package-lock.json ./
RUN npm install
COPY . .

VOLUME [ "/usr/src/app/logs/" ]
EXPOSE $PORT
ENTRYPOINT [ "npm", "run", "watch" ]