FROM node:12.18-alpine3.12

WORKDIR /usr/src/app

ENV PORT=3000
ENV NODE_ENV=development
ENV MOUNT_URL=/phpmyadmin/

COPY package.json package-lock.json ./
RUN npm install
COPY . .

EXPOSE $PORT
VOLUME [ "/usr/src/app/logs" ]
ENTRYPOINT [ "npm", "run", "watch" ]