version: "3.5"
services:
  phpmyadmin_honeypot:
    container_name: phpmyadmin_honeypot
    image: phpmyadmin-honeypot:latest
    ports:
      - 3000:3000
    env_file: "./.env"
    volumes:
      - ./logs/:/usr/src/app/logs/
